### ISSUE TITLE
What happened to your discord server ?

### ISSUE THREAD

**Issue by ElektroKill** [jlagarespo/jlagarespo.github.io#1]
Is it deleted or did I get banned/kicked also why aren’t you online on discord or respond to my messages ?

**Comment by jlagarespo** [comment]
@ElektroKill i knew any of you guys were going to ask a time or another.
My account got terminated. I deleted my alt too after that. I probably won't be going back to discord in a while. A lot of things are happening irl... in a few days all my messages will be replaced by "Deleted User". (If you ask why i deleted my alt and why i won't be going back to discord in a while, it is because as i said above, i already have alot of headaches irl, and with the fact of the account termination, i decided to go away from discord.) Maybe i'll be back soon™(which probably means in a very long time).

**Comment by jlagarespo** [comment]
Oh, and i forgot to say that my server likely got deleted with that termination...

**Comment by jlagarespo** [comment]
(ik i shouldn't have deleted my alt, but in the moment i saw it, i was very nervous and i was stupid...)

**Comment by ElektroKill** [comment]
that's sad

**Comment by jlagarespo** [comment]
?
bug reports?
wdym
what channel and what bug reports?

**Comment by ElektroKill** [comment]
Revolution Bug Reports

**Comment by jlagarespo** [comment]
Oh
idk, i didn't send anything there in a while

**Comment by ElektroKill** [comment]
ok,  is there any other way i could communicate with you without discord and this github issue ?

**Comment by jlagarespo** [comment]
yes, that's kinda weird...
idk
i will close this issue for now

**Comment by ElektroKill** [comment]
ok

**Comment by jlagarespo** [comment]
maybe i will create a new account
or maybe not
idk
